### ISSUE TITLE
Supporting different versions of an API

### ISSUE THREAD

**Issue by BavoNootaert** [erasmus-without-paper/ewp-reference-connector#18]
Currently the reference connector only supports one version of an API. E.g., xjc generates classes in a package of the form "eu.erasmuswithoutpaper.api.(API-name)". Perhaps this should include a version number (major version should suffice), since not all hosts will switch to a new version at the same time, and a client will probably want to (temporarily) support both.
And, conversely, it might be interesting to have an example of implementations of two versions of an API, served at two different URL's.

**Comment by wrygiel** [comment]
Cleaning up. Sweden, please respond on this. If you decide not to implement this, then let's close the issue.

**Comment by mikesteez** [comment]
We will not be able to implement this in EWP 1.0.
