### ISSUE TITLE
Incorrect due dates?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-reference-connector#28]
[Current version](https://github.com/erasmus-without-paper/ewp-reference-connector/blob/7f94ce2422883ff3581ecefb60e56a2f3f65f9ca/doc/activities/WP5.3-Development-of-connectors-by-WP-partners-starting-from-specifiactions-for-reference-connector/WP5.3.1%20-%20Management%20of%20development.md) of *WP5.3.1 - Management of development* page says IIAs API is due in "JULY - SEPTEMBER 2017". However, my own notes seem to say that it is due in April 2017. Which information is correct?

@janinamincer-daszkiewicz

**Comment by mashod** [comment]
I got this dates sent to me from Valere/Janina as i was not present at the developer meeting i Warsaw.

**Comment by wrygiel** [comment]
Ok then. Perhaps it's not so important.
